set -e
python src/process/process_update_labels.py
python src/process/process_update_labels.py
python src/process/process_update_labels.py
python src/process/process_update_labels.py
python src/process/process_update_labels.py
python src/process/process_update_labels.py
python src/process/process_update_labels.py
python src/process/process_update_labels.py
python src/process/process_update_labels.py
python src/process/process_update_labels.py
